version: '3'

networks:
  local:

services:
  webserver:
    image: nginx
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - local
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  composer:
    image: composer:2
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - ./:/app

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - local

  db:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}